---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: talmox-hera-home-karlsen-fr-certificate
  namespace: gateway
spec:
  commonName: talmox.hera.home.karlsen.fr
  dnsNames:
    - talmox.hera.home.karlsen.fr
    - '*.talmox.hera.home.karlsen.fr'
  issuerRef:
    kind: Issuer
    name: cloudflare-dns01-issuer
  secretName: talmox-hera-home-karlsen-fr-secret
