---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: karlsen-fr-certificate
  namespace: gateway
spec:
  commonName: karlsen.fr
  dnsNames:
    - karlsen.fr
    - '*.karlsen.fr'
    - karlsen.org
    - '*.karlsen.org'
    - karlsen.app
    - '*.karlsen.app'
  issuerRef:
    kind: Issuer
    name: cloudflare-dns01-issuer
  secretName: karlsen-fr-secret
