# https://docs.cilium.io/en/latest/network/servicemesh/gateway-api/parameterized-gatewayclass/
# https://blog.stonegarden.dev/articles/2023/12/cilium-gateway-api/
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: private-gateway
  namespace: gateway
  annotations:
    cert-manager.io/issuer: cloudflare-dns01-issuer
    # service.spec.externalTrafficPolicy: Local
spec:
  gatewayClassName: cilium
  listeners:
    - name: https-karlsen-fr
      protocol: HTTPS
      port: 443
      hostname: karlsen.fr
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: karlsen-fr-certificate
    - name: https-wc-karlsen-fr
      protocol: HTTPS
      port: 443
      hostname: '*.karlsen.fr'
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: karlsen-fr-certificate

    - name: https-karlsen-org
      protocol: HTTPS
      port: 443
      hostname: karlsen.org
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: karlsen-fr-certificate
    - name: https-wc-karlsen-org
      protocol: HTTPS
      port: 443
      hostname: '*.karlsen.org'
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: karlsen-fr-certificate

    - name: https-karlsen-app
      protocol: HTTPS
      port: 443
      hostname: karlsen.app
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: karlsen-fr-certificate
    - name: https-wc-karlsen-app
      protocol: HTTPS
      port: 443
      hostname: '*.karlsen.app'
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: karlsen-fr-certificate
