---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: https-upgrade
  namespace: gateway
  labels:
    https-upgrade: "true"
spec:
  parentRefs:
    - kind: Gateway
      name: cilium-gateway
      namespace: gateway
      sectionName: http-wc-talmox-hera-home-karlsen-fr
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            port: 443
            statusCode: 301
