# Encrypt: sops -e Secret.cloudflare-api-token.yaml > Secret.cloudflare-api-token.enc.yaml
# Decrypt: sops -d Secret.cloudflare-api-token.enc.yaml > Secret.cloudflare-api-token.yaml
---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: cloudflare-api-token-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./Secret.cloudflare-api-token.enc.yaml
