# Decrypt
---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: cloudflare-api-token-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./Secret.cloudflare-api-token.enc.yaml
