---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: gateway
spec:
  encryptedData:
    api-token: AgALoFtmS01CBPXh2V1iOltX9QuA2k2ncrbdACnK4m5vVykNtcMNwbuY0GeInAztRazAHE9tcrQ8RlDGDoy+AFarkU1umlrj2ujM7560X1vRghlZ/4IwGl+8tzR4hjC41Ra5UGenc+2bZkhMb8sgdbEMliNYSzKv2rMUYR6XtmIGZS2/6Dxbs/X9JGO3IuYjVnXHkzfQ7YsYYS1LAz4oZlBKQAVHzXp3jlnz16Yq5T0jnJ2TOuOgJ114WPMUB0UWPkXRR+h9WaFaDzi9873m0lwE22BqyyqGWp88hvopOqxqR7MinXPGSCp9d1GgRXA4AXg+EX+OUYNpkrf8lvuHyPthbXwybGaYoAJ7+AdVWZikaKyqK1PPPPSwisRg8cOw9+kM/Um1yI//Q5J2DyZVMCTY8qmgmAsGd73fR6J/xL91c5UM1WUpg9lgayZ0oE8Nqxl3YTvM0qAaxVceog/mL6vMO0jUVaCYhJhWSfZNyzPjcJfLZrFCk+NCxLO9f1ENiOhrHZGUg9BrFb5Rt+6HvtPCXUpcXR13xmHAsLrb5IYUX+8Yr1glf8M1T3BXaMeK4neZ2YZ+En54TKM1LRetdcon1FwOf33cg9mfe1FIndrcgwi18qIEwDsQYajWHchhqp+gzJ0zLhYnjB+6tStqT88KAhufoLJjyDoBO/SjmPmy/WLouwsR0BSOdYQ9v47CFK/ABeqzysiMnbClPBFh9hMH17JrOZqDVsK4Puq6xMr2Yyz6is3XSFSD
  template:
    metadata:
      name: cloudflare-api-token
      namespace: gateway
    type: Opaque
