---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: gateway
spec:
  encryptedData:
    api-token: AgAd3+G0NPCCtLIOrL0nCytAzu2uGjlUUpAMTpS819/jnBrMGx0uzAqooZqU4TLSflIp3xWDQeH3MDZWKjtI1mQCwWariyIbm+jbeok2rj+cZPA9vb2XWXTGJHedTL+OxKIGu1sGmhWRp3btZobY/PPqClfzYJpSc9PtrbJDydRihbzE/gfs3nKNywcDZsqlgWrxIGLVUQLtX/xFF3/MmOHWMxj3qVHyfTCapquN0nMk3LWoIG4AM4WvwVAqvCXorc7CHaT7pDpCjIlBPM78I1DuweuL6pO1Vu6x1xMlTK0RiEIGhsCMt7nUjpLF8OIxaiG3j3KrsobecuBZizYy8+2NOLK2c9TOU2WsAaniKKe9sXsoP9mosRo8UywLbLxeEr656WFwb4TTCTNmCJRMPaXiyoqVtbu778O2yuz15VVTrWLS7EclV817YGnQy7T/ULo9JoiASRP0pd5OSrfiDoYjBs4tAgX4wA5iQBPQp/mKAQiU8FGe3fj9EoPhGQ5msbXXBHlTWWD53K789kW0xmd78PO8AIUP6qgcHKQDz/0lgEhE467UBrRla6mXGriraB8+R3yfFDqT4JAA1ZKVkYTcQE7s8RwkKKZ3iBuu1HB64juoriKImMa2jm6rDqMVj7WRxjyb0WXaLTtNcRy6ht0mzxat+pxTdI6HAyUAKlOgz2Pscnagu0AOaxdF9XghGccPK6iUe1pDSwB0hKeHt52WEGCLaTiZ81jHt+J0tXB0mfh2S8dSXCXY
  template:
    metadata:
      name: cloudflare-api-token
      namespace: gateway
    type: Opaque
