---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: gateway
spec:
  encryptedData:
    api-token: AgAWHb0DEeh/irj7Lv6/lKf7ZEkTNI+YgrqXo65emqFmgySKHTJBlgIoith5ZyOkvFvzztSmDJRMjuiCmKQFuj1L/cs8/OvpBzMsobrTRe0L2YRAbR+5S/CnT8SCh3YcRXPSi0QSA/4+Oya1YAiDJel3OTjbN/WSilZLg2goYkTb4dNfuGXEy/x7ual9CZR1MZY5TTsFPfsAzYjDAaMCmPiwneCq/xHpdgs25Q2iL2oM3JP9xB8yIC+CSHWqnH380PlC5k9PYxs3lD8katXzmB8p9qj6SLc67wC8NeDnIf2uvI7KC4AD84VNi6rMWV/6MYSwdRuNy5JCVukl+yYU5iUaJy4+YvhSMg50zOMSFGJejpMEOHARcNpJaSie75MGOYwfkqECOVbbV9swBVFCgvGnaGdJCoDYd37tQYjN5bMx5eJR7xJWWBxEAXbUIqFN2BJ7oJBtfF3qNKKoFdMSwYcVP3vlbLzf1y0XDnfJvgxx4iGLR7e9PMYRbAYMFzl4mJliSvLzQo3/th4sPyrrsnI55GS/wV1+UFkLF6CzmT42VfM9DTPVm8SOgDL2H25mr/M5pWsykapwXYqT/8vrvFgWDA2KuvkSbrpBg0hDmi0elCFCCFIvPTpbCNZoxCnMHZYJBbj7k2soXJ1RO3aaV0r/e3jbJ0l3D6JM/VHjE1F+h4UmqLqIkeK71h+A3L0bZ34nbvF5ASPi8lKkXMET/oChUfjHbw/8BGaeFGlVhaVXSyn3Jmgnb13D
  template:
    metadata:
      name: cloudflare-api-token
      namespace: gateway
    type: Opaque
