---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: gateway
spec:
  encryptedData:
    api-token: AgAhulkTPTCAu+kh2bj2ro+khpBqgPaXQ4JWgeSrmgrgmgnwwMq9mZWQCI+9Q/q0xslyRNanFD/f8Mgg0abvGLq2dF/hMd6R/NH9ojXbAsbH/rfFd0JlWO+YBwogkfbVYFS8tDuDEGErVq6qY7ruIVutnb39x9bLeAsRSroKJ/00WMALkkgkyi7z2ScELcMCxoPpEMO3FMJYc6PMBYNR4pD6Th38jMxzzcq3jLLO53lmIamfVz+Bjcz9mY16uRnW38DybqgE4/mQaxVzoChnt9wYO+2M7reNjx1bcpwBwsDH/VtuACDbxWHBD06XnjVa33SVwawi+Fjxr47futaW5SDWimJkejMEBha+CN0BKHrjVfpYXXz8fYYcJX8lRigYgK3uGCN3xAGo+3KV01hLsZJ9S0oQ25L/sYs9tHJ1I/NFIdZe0YHI5s9Kr1aYUzSAkhU+rGXG3GFlk7pxy729S/vPq5HFdUtAmaXRX8M7ifxAuS9k5AMudE21CdOxPJmZLLv9Nir+TeTXbGofksUXn51dAqeHFpEKAvYLC24ptXe36TNtIu9wKSkoK11ZET1VcAB2xZ5qr6vKA0FlNB8pFArr8PWovqtAzzyPvuzV0GzbW1JFpBY0zJLe17oxJHBkwWwSamLAVvfOByKwrjsx0XVkg3gJApKLGqO3nvVLAv8EPbAYf5mKLprIayXIuTwOlQdbapaZt7IxzqW8i7lvIuTj394ypslEcU24E5KL/A8GqDNHc6VW+x+m
  template:
    metadata:
      name: cloudflare-api-token
      namespace: gateway
    type: Opaque
