---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: gateway
spec:
  encryptedData:
    api-token: AgCGi1XWMKtTQnCkneoUXIvT1tg6cHtC7yL1TDEUsvce+N6zobksUTN5QSt0Pud4lBmm1DREoSq1LZ8wstvLcWteQ7Ln2mQ3fwgv2XDbda/V9uktXfuJl5hX4eSk8k9aVZzlvxr1CaeM+0UVVSvczwQqNe7cZ6CNSo89C3fdwXdvAIMn5rPd2Fr6UA0rDWC8wOXg9xzLOLHGjPW9tOkJGZZODovLUrYcgMkTJeAYMTbVpygi6MorOfR6X47dK0WwjrC+xz7fmdk7qkR3OmIIYpDUVHSI1B2djIj9CFB3sFhYc0PhA44j47N+LshygFki9IL0dbouRgSj5iX+M6gSFZrREyL3DlKjCOwQTVXw2PF3Qjr4TFISPcyC/lTVzolGCKRpZwBHgOVa3/IRP8Tl98hXlJpQBmqNboZ9odCOOw6CKB7d79Qwk3jCwtAvTqlUOOnfJLcYxSlZtbJZPpJFbzN+6vuJJRxLuZdnJanH9Oa4w4q/t/tvZGXTDJ0VlMBumuViGAN6Jt7D4/a8U+tAh0d5mehqvmbMZ4DO1l06wWhqG9ULTDLRoAI5FNUHm2/GydUcVac03vm6fcLVAx/SnFDgh/WCAxZ9P0w8hGLoLbYvz/jiHMfu2gI8CaWZgAVhFIzfYvRgOZhsT3C66P/8DFbpCHq29LvEFBuOlFiBJeapIKvwRIZ9pqIgQEcsjvc8BwvDA8P4B65EK8yigGPTvuLAWYoSdfLFBjpJXzZltb4Xn6jCGzpUM/eJ
  template:
    metadata:
      name: cloudflare-api-token
      namespace: gateway
    type: Opaque
