---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: gateway
spec:
  encryptedData:
    api-token: AgCgM5jpjM0BpbmTxnPzwA7VAkD5qyCage8FsLqKgBhb/NWhkl5f10R/TGOkaMOgmWNKk8EMGuJIeZ60I765xYv/8YSzD+D/g6ZkM7KPbt6fhWNBTfiHqZbeeaNCdQdglaiEvjCi3Frbwf/rWiRxfexOGn2bYlV8Vb2XYpMJxyztOw4sexxaZ0mud5riogu5Cz7lFsXOmetLCvEtGROFQgRM9cNypc8DiAgn3eFdo/8AOa5Qw2hRT6AzQHNyijKHvCnMN3Us8YWU9SkYZoxCC2DPhUKq1sIRx65BKmMMtu/D7fVjcpvY6rpj9dJFpUPDZhDzynXyt/a2CedpzJ6IuUOh6ofZiKk2O+ZBeZIIlm9XLQQ2/DYXuOy4LT9pJnhnsjSNqy6PNMdBznIX9pAdQ5l+CLd6UuuNl3GtxhZ9oL4G9r5m16zSbX5YZKlFujXOwMFmvtrv8Hu1LPGfyfLLsmdnoVhqPmVhKWINT8HwWyB1ZmRgbRx6YDfTFmedJ0MKObjmXxziP7fPgMnQoBlfce7qUQX0l4cvG1jbDBwffEMRW4/H4nSPZ/nimP/dkirdJU9se3MfD1AevbY/yJu43yevtBZwSYgdTRrxxAaSEibuVE+iT+9iloNOiGWfB1ZHEbKrHQpuXy8dCNLwKi308IahlNW6mP7HssAOSNa4xsWI7L4Hdk/nLsnEVet+lwQxEy+uIpBxFQd5rzgDqgUJ+99ciVKvVEHgMw0E94Cep7xD605dpDJj507A
  template:
    metadata:
      name: cloudflare-api-token
      namespace: gateway
    type: Opaque
