---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: gateway
spec:
  encryptedData:
    api-token: AgDZYb3IFg7WMd4W2TV/7bSq+posqImCEkElVD7DinHuyAH+C1rUdby3BrwtwxeN4qZgcQUV9NXMds02Ez+CuRM/MowomkASjWvxqQUqr7bDxjc8H9JXni/+V9bUkk+ZFOhqsszHOqz9Oh3PGCJxiRlUDKUQhkSCBWSxOFLNI+YFz3KKqUFsgbeCmQDhrp0KZUQ0XKiOw8h4UaT/7KC6LrIEsrFoJfs+YmVqZL4Shn20/8hbmv7xz2HDs/ex4nywMx/payHhFdkWgsHni7uBnQ+V8BaIFa6WK1iB6E4l9M+BrlEIvLx6m0p3TKkdTe7dRiJ1Obc5boj/9bVUep6M9CsNc9LtcuIlycoYUTEj49ST8tOax/obX4BJ/4QpKugJjPoZCFs6kLpVvvnUt/rUEYqacDUyMWSYWPA/r+Vd9qf7EiDMeRdTHegaV620LmVpljttTzQpKZWIx+LHvAMDg6lKtFktbz6+5yEJjeMknpD/Fc5MS9NXnYQeCYPNKltjBOTlbO2LTp5UPnrwgs1QXvpbxci8B5OtSh0wfDa40h8scT19260vtPA9GAwxvXelIl9XsVi/qGtL1P3fFy393LR/p0GAP4CdYQaDTsgo4wN3H68ph5DWm7kTG9Lzh2xkQqMuXWB8Y3O9RiTqRS9P6FUf2dHWBFvobfj8EEY+nYM5dOZfXkaOiOJ/1aw5jNBb/bsnpCKKBvqYQ+yWAzzomm3LzmmVle+zVMWZ8Yzw5bmA3F4tw/CbDoMv
  template:
    metadata:
      name: cloudflare-api-token
      namespace: gateway
    type: Opaque
