# Encrypt: sops -e Secret.cloudflare-api-token.yaml > Secret.cloudflare-api-token.enc.yaml
# Decrypt: sops -d Secret.cloudflare-api-token.enc.yaml > Secret.cloudflare-api-token.yaml
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: gateway
type: Opaque
data:
    api-token: ENC[AES256_GCM,data:M4L1eJkDuk5racTb5X/sWCfxV1VjwM1gTTIdz9UQMSpdLL6FhI/LKt4RZgMUmNM49+8jpgLIqXM=,iv:MwX35RG0HFosDCO1mPDLrJPFeO37h1aBmZlgdILZUyA=,tag:x2FcBpOtBFDCDistYtp+XA==,type:str]
sops:
    age:
        - recipient: age1gxk3ylhwfwe0nkhfu8pr08j5axz5y6qm50ntp0ncu0l6cx20fdrqw36n8a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMjJMQS9vbXR2d080NThC
            VTFvRjNzY2FOU2lDdElkaTF1KzBqRG1ncUFRCjJYOWUyS2Q0eDViVkYxY0FuYUY3
            ei9pdytySVI1NDg3N2RyRW40QWtqMzAKLS0tIFNTSEkxeVR0VXROZWVNRG45U3R4
            MEtVR05VMFozVXJDN1U4SFdUcllkVjgKhY8M+UhmTQowrnQXSxrAY2yIZpYzsYR+
            ZYgyWHAbGv3GiuyBRPXf9VPtCJDVMsi05A7bHu5cN7QANiQIuzdxgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T09:39:06Z"
    mac: ENC[AES256_GCM,data:n2fON3Dle2tiCW5paVSOK3UgbfePNTgLNtygnTDt6pEOxv0jHpBKzHL+NhATZHg3aV9tC8TAAQ9adE0i2fbYAYJxdeUAZEFVY72hGQcvhyq1aC2j2eBPwe/tvceWOBBPRPREdA2ZBKqJbueFTWy2G85zBwxSH8qO0ZLBNFwTX14=,iv:zyI6iWTh3xIyzHycit5n2W/v0XpHaPlzz7iAAN1QGeU=,tag:WHenXvH1Tyz/mVr4d8lubA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
