#ENC[AES256_GCM,data:re95aDOBs8CUoB97/FeS8uZ74JlseDiJPGxtLDR/XdXT4+Jb30EH7YKZwe3SSCdj01hdcJD40FnVwWOuxeMhB23bW4WsAEngSc15oEU1Of09mvX77/nhsqo=,iv:rt/fRjD3BcJmmNEf8I0DHJaKQxlQna5T1q6FXbsEmf4=,tag:IheBSnVKP+Z5e38QTxt/yw==,type:comment]
#ENC[AES256_GCM,data:uwgNvV/nFv0yTKpjJemfiqps2QPanAqetA7WRcsDOwVBCeGK6P0gEmm0xIarBSjiKWgndcFH3Mi+qkOE5bb4fLB9c7WlKyfjQPImg2XYQBNw6TvH2UwHQo0=,iv:07rdv+4krnoKIJcrSCADgYYbdc1/UXRbiSmLOOfF9R8=,tag:nBHFOHdsMT/DpVKEqqjPbA==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: gateway
    annotations:
        kustomize.config.k8s.io/behavior: replace
type: Opaque
data:
    api-token: ENC[AES256_GCM,data:BjOy6o0gU9NULlv0g1z/GoJ6tm54Z4bC2NWmewgw7Dnwdr8xaZQM7gm+a5BisRRLpplqhuYNRSU=,iv:gpj/OXNq3fzATL+BymrVN2UyijwQ/30b3egfsX27Vvg=,tag:jEDLJA5ZjNDIq1/pGbEykQ==,type:str]
sops:
    age:
        - recipient: age1gxk3ylhwfwe0nkhfu8pr08j5axz5y6qm50ntp0ncu0l6cx20fdrqw36n8a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWR0RnbWt6enV2cFdiWWJj
            NEd4OWRMb2pIcUM1ZVdjSThMUzdJUDlBTWdvCnBqNUMzM211WkFQWS9VTG1oOGx1
            Q3ZtdzlQUjBrcXhVY2NjN0pKa3hQb0EKLS0tIGZCSEJqdklVYmtTdDdkVWVPZCtk
            SkIyVDIvMTVUVXNGZzBCOCtyYkt6d0UKHhJOUavEg1dDbVum7YK3y9vVwksBvenc
            BjqKkfjVqIvrs/Odpr6wViuA2xIzlVeNsJsZI6wf/dCTjQXZyPYI1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T14:37:14Z"
    mac: ENC[AES256_GCM,data:2vwgoWAZENyAzZFv8a+tX52jmP2OtzRD+PgxJH4TCYBD2Z7PKJvD2OHQ04riOGVoAMVwemyUGBU0bqL0JHs7cpaOAB+BYeKqDLik0NCbj6k++0q294cFYx3CIpFe7+iTTfkV+7zlPoT/kuuqhLLYSw4tbduYvX3uhBZEUJX5urs=,iv:Q/kQRRxyca//3wmvWERJfgZ7U5TXQA/XSKEVS5nTsvI=,tag:B8d1mznlK7d+jFG7xyRuLA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
