# Encrypt: sops -e Secret.redis-credentials.yaml > Secret.redis-credentials.enc.yaml
# Decrypt: sops -d Secret.redis-credentials.enc.yaml > Secret.redis-credentials.yaml
---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: redis-credentials-secret-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
files:
  - ./Secret.redis-credentials.enc.yaml
