# https://argo-cd.readthedocs.io/en/stable/getting_started/
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - ksops.redis-credentials-secret-generator.yaml

resources:
  - Namespace.yaml
  - Secret.redis-credentials.enc.yaml
  - Service.yaml
  - GRPCRoute.yaml

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 9.2.1
    releaseName: argocd
    namespace: argocd
    valuesFile: values.yaml
