#ENC[AES256_GCM,data:nayL9tGkpAKjAJJsunozjGSnOe8lTuztsTaFlFJIYpnYLTDoUB/31D1j1Lwr9zF9l+0J9OumfkziNW7IPV8SAph0D7fGdiMQHY8MR1y7JZYgqPY=,iv:EXNjpl95WRvM19bEQSGS5EE9+xi+J2lkKqBvFDWjPqw=,tag:saunSZL7mLEzO5PQbf2NSg==,type:comment]
#ENC[AES256_GCM,data:+6eYCrzfzJeQBwE+zSNj2wLApQQRZc5WnOkwIenN/fJYLI6zrq+Z4zTZGtMgKo7dmAwSHf90IiFFKZXNcDbIWHi8t8/RjtAH7FwoOIH4pE9DqaA=,iv:JK3QEDgTT+a5mGd6hv7lLebOAauC+orKb2xcImKdnXk=,tag:8GmbawMn1aGNGC+/yMhV1A==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: redis-credentials
    namespace: gateway
type: Opaque
data:
    redis-username: ENC[AES256_GCM,data:s6PhePjw,iv:BAx3qAZGwzhL9D5i+rGRwdjba8tGDvQSMXMMSDcTURg=,tag:bcJVE8mfebdPylJlE0I3+w==,type:str]
    redis-password: ENC[AES256_GCM,data:HY/dN6H354V1kLma+j+TuAKVBsiel8lfdyMNWTVVwymGE17A+6eL2QsvY9RZXJxZ,iv:6Ii/+zPbdOnyosf+j0K+ITi51lGmsif8fW25rE5Exlw=,tag:Iuw8leTuGYILCATJTJwSaQ==,type:str]
sops:
    age:
        - recipient: age1gxk3ylhwfwe0nkhfu8pr08j5axz5y6qm50ntp0ncu0l6cx20fdrqw36n8a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkOUplKzBoY1hxU29MTG5l
            R2ZiYmF3QzJFN1lxSlhpTXNkOGZuTDBLUG40CkpLY3pkR1N1YXF6UzJaak1lcUtO
            QjZ5bVEvWHBpNlEwTU0wTHY0M0kvSVEKLS0tIE1KWURKNzlSRGxRZU1Ba2xrMWhz
            MVZSTnQ3WU9lb3ZtQ0NjaG5BVGZWTUUK8I4t/1Jf9HAt4sGXf1pmkutTvF9zzyij
            eudvUeEb5KUqAmuGkoPXPN4H/koEtYLmwbKyLSwjrX1pdr26WUVkXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T12:15:18Z"
    mac: ENC[AES256_GCM,data:NA4KoCvQ8Z9vyyuvRpnsCnF0UoyrJ5t+tympa36R04ADRIQSPAFAZ6lk0Fh3Oa1RaNFzheZnbRGs/lzyi4JiHN5j7HckcRY8LSuNSuUY/vYLbgarE5+dgDPlRLWbAqRyBahmsKKPMafmquwcq1XBqWH2+ioUGxTOBfXzr9IA/eY=,iv:iOEjHNY61QC4n4J2SY8gcUBA3QuCUBdqI9hXqKef89g=,tag:7ctOsmPlf/pi+bZJEZzlTQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type|comment)$
    version: 3.11.0
