#ENC[AES256_GCM,data:DbBlQVDG0W0C53UgyjwmP7+JFVr38/yNZGBpMR5baoUzlDQh03SldRIrr8Fr9gfMPDQfI2ThPc4K2/qxMwJaMESzOyVVlCfXuzD4++Bb2PyVpiY=,iv:uDnlbDw0ckN0d8oDdN1jpmnnYNykEAnGgvXGoJhU8ds=,tag:Ny08tRkIl68OrS1x7y7ohQ==,type:comment]
#ENC[AES256_GCM,data:Ea5vJpZ7VkTYXoUMmLxZxZGxnw8Bl6KEDsug6XyLf/AVbEJsp3POemG/97vVcl5lT6geJS3suofL+Aj9Fugj9lqNV7mGtrjm3Hf79NPlCwHW8l4=,iv:DeZQzf+ZZj8cUB7aAJw8JpHNHF26HNgxaq/o9pTgQYM=,tag:/QWGp2a6ULICp5wl0lc3zg==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: redis-credentials
    namespace: argocd
    annotations:
        kustomize.config.k8s.io/behavior: replace
type: Opaque
data:
    redis-username: ENC[AES256_GCM,data:MRNCTyzQJei0NzJM,iv:EX+kLTsr3XthzBM+GITffXQalxM+bVU/GMcfJc/FpAY=,tag:hOhNxGhbP5jqJxtVy47wjA==,type:str]
    redis-password: ENC[AES256_GCM,data:xTnA6pkRKQuF0/AnDLzfkI/FOOI1upvGX1pY/3YstanzKFQq5fPVMkhCCjLhtOzWFatPxgvRkj+5V69SqmXc10ylZ14=,iv:6+FZyMXZGNjV0wlzd11lQa6RKPsvfPwgkBDA/38M3qA=,tag:cRPvMPTT33zGXe2zQP2tiQ==,type:str]
sops:
    age:
        - recipient: age1gxk3ylhwfwe0nkhfu8pr08j5axz5y6qm50ntp0ncu0l6cx20fdrqw36n8a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Zllya0twbVlBZnBPOVht
            ekMybjNCQVFreUVOOWNLaEVRbEYyWk8yTERzClN3Y3lpL05OZ0JGaStya3RVUGIx
            RkRvM2JHUktwYUYwd3pwVUZEZ1FKTUkKLS0tIENNOGp6WU1GQ1NDU3psY1dsLzlu
            SkR1WUNsRHpodm1qLzZRTThheDBrN0kKxoSyQFEuFdwl73OFzqJYpV6/xO4XKh6s
            gSe82YDHnFXAz9O+OWmZ3743LqppOYqwFvFBbU5pSM+jhi2s3N1jRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T14:55:59Z"
    mac: ENC[AES256_GCM,data:vFqxc4iVCovU57vcoO/qCzoMGKC00G/V+DE0/a+o/I8aZfajRJE5m9YU3d/V+woZvCuf/hpYkeU9Of+pA/jyobK+Q5fpx/JDk3fL78lQWN32gSPN6+wx2CYTcFTtX62K1NqJCG5t9L6o3HMCHlg76nb5r9VRA8NEZw0lzgV+4i4=,iv:mkIt2Bpd8vYS9YwXViKdT6GkeoI8uo2dVbGf93Ee7Fw=,tag:sH7BbrK1fEVeEeSiXeLdsA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
