#ENC[AES256_GCM,data:rOSrbHlGeyjTeCKoZp+a4v6JsaXsbwXUunI6jzylUkLFm/wH6+iE1N24U5uYPOsRFLqZGKlHaqFtVFxy7aoD3IRawL0yRRy3qTXAVc5MN4BmgAE=,iv:ZIswDfGSK818NLNMBkflDXeE1UeBLGsXNwNqrWuq0Zc=,tag:9Z9hkqK0A1QqYjPDnaxiqA==,type:comment]
#ENC[AES256_GCM,data:DSHekqYzEm0nwH+zkXPjSFAwG4CoPLECdyOYGt461sMrWwhzZqUBWofTTXDXPheDWu8uQxk7Y+671wEvs4S6IaaHzjk/fE15kfQjpDD43vHM05E=,iv:xuckfWKQGZsbIw9x65CMXegYE5KzFnJW5WckGN1y/kU=,tag:bjT8FhSdgDXZI43eU7KMAw==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: redis-credentials
    namespace: argocd
type: Opaque
data:
    redis-username: ENC[AES256_GCM,data:7SSqFD2V,iv:SVMntFATftjR7ojkbMkmv/ET4tbHN0j8hsIzQyoVpfA=,tag:WVYmJw0tmSP1HMLpjahmnQ==,type:str]
    redis-password: ENC[AES256_GCM,data:lyegN9MoG+zo1JB1059ZkP5zJ5ccafacb1X3GZ7b6f3JmT27TGtCmeC6StXFmDgU,iv:PrlQWyjH9ttUtkPmHzWRmgKytievxtzHvQqq+MsktOE=,tag:6weeZi1sgo0fJu+nYlqomw==,type:str]
sops:
    age:
        - recipient: age1gxk3ylhwfwe0nkhfu8pr08j5axz5y6qm50ntp0ncu0l6cx20fdrqw36n8a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxTm05NjFRQi80YW1rWEJU
            by9HNVgvU3lUOE1PaGtHNWwwWFJZZlFheXdBCkhhcU1SM2NPNUp4NXNmOGdDY3Y0
            QUFqVDVjUWZWdmlZeHVwQ3NsbDhXK2sKLS0tIGZHNHEySHJJVXd4ZUNjS24wTmdm
            WkRMSm1Qbk8rMmZjWmQzS0dyT3FMMGsKyJhDhGXlD23FPrgtgchqWv7fJ4U1PTwy
            c/bvVmyJ9NYvR+wYBZCzvbONNKZdA+qKBXEdRfReMmXEUjjsON+F2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T12:19:40Z"
    mac: ENC[AES256_GCM,data:FZnrzXLwU8mgSWzKAxzIKthBekZDF9H+ViCnHK0cedXli1lXNl8RC6ExDJapd5bE8W9dkTPBl3/5dVrG8ysziBepHSyR/+3ablKvh7d7AGGrB+XggRdfJWN5cUh+tWmgUxBuPZP2SWCCVlQKhxwo5P8xgXXrUmqGVrwZU5vxU+E=,iv:hzX9BYgoTnEZIR++KmaNo1JdBQIyOgAKQPj1DbmAvKg=,tag:muyyO+oMUfLSWWOg2cJWcQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
