#ENC[AES256_GCM,data:BOSdCQYESwUr6oJmoBinkpdzl8eDbsbxBCblbDuFkqE64y1xNXM+etzxDw+PM0XR9oqCDsgP8/H+I0ROfzxcBuBGm6iAul+cJD7lniM+n5Wddso=,iv:NWsrkGT41spmp87xP6ADvya6EQtzf6gmKLqNMT6wHdg=,tag:yVi4+p3hb5NabMsgcf6kAw==,type:comment]
#ENC[AES256_GCM,data:qWaG5+MDAJrilABRFbmztyNvVqB00KNaTDyLscspw18VEeb/onoEquxPgHD2wUrzf3yDrSQXE1pkBU8/5fOBp3iEzd5RSDAlkrZG3SjQjtRjJx8=,iv:sGunJF5IXgvkNzL1JqUmDupq2epmn4YXhEP9l0jrYK0=,tag:AaLPlMJmoNYIgwSMj8QkUA==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: redis-credentials
    namespace: argocd
    annotations:
        kustomize.config.k8s.io/behavior: replace
type: Opaque
data:
    redis-password: ENC[AES256_GCM,data:sviywpyv8BTfTUmL9YZS0GNxn8OiRsDSv4RxgcDR+bCO7GLT/NIxZVKs6A/HXn64AeWVy2BrENlWSuBvw9STkQ==,iv:gdeorfG061aHnFPk868H1Ixt82TaHZDmHUA+UP8JkDc=,tag:zgzx1WkVUX84MitCUJmJ8Q==,type:str]
    redis-username: ENC[AES256_GCM,data:Xk4hFYtqPR4=,iv:pjhMP+rPfIrZWf8DeNbUwFY+okWhdQs4IlJb/2IQthc=,tag:mc4IUFy79v9KU3s7a9pKRQ==,type:str]
sops:
    age:
        - recipient: age1gxk3ylhwfwe0nkhfu8pr08j5axz5y6qm50ntp0ncu0l6cx20fdrqw36n8a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RVNwU0tTT2taZ25uVVE0
            RWxuR2FhRCtOSjJudkJ0WjVia3FtamJ6aWljCnpLQ3gyM3hBaGVtTFF2UkxKUEFT
            aGVRbGNxT3ZwRDBuY0hvSWdUaXp6SmsKLS0tIGZqM2hIWVlZdy9aWlgvcm5ReXJQ
            Zk5uMjVqVm16c0RycUZMendtaHo1Tk0KbZ9wpHRTP7Uuqv1OXMm3um6EcyErAWoe
            bdcuzQ1ahCxkfA7JScJ+6WDcS8mgZm8b03zcBFJD8754RVgfNAm0dw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T15:41:28Z"
    mac: ENC[AES256_GCM,data:WNNYoW6np53UAbP9g3HFNpNXvkZzxnSfE7RZerf/xYJ8sm7Pot9G+lXVEfuy9ToAO/ZDvCSil8UrL4ZTCtY7hLXb1G5UtUIG7Ka14jx13B5VWy9ZD7D5qf2ZCQivmlXjUSk/VJQpDzfNEeGKpclu57f0tpNR3KLtVIZzTrxBBtU=,iv:3O0xlsSPo1KR3rwleae2MT9uAM2ALHDwVTU+6UlAkDE=,tag:BoPWKyy7M8c9OP8lNh2AdA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
