# https://artifacthub.io/packages/helm/argo/argo-cd?modal=values
---

global:
  domain: argocd.talmox.hera.home.karlsen.fr
  securityContext:
    runAsUser: 999
    runAsGroup: 999
    fsGroup: 999

configs:
  cm:
    create: true
    application.resourceTrackingMethod: annotation+label
    admin.enabled: false
    # https://argo-cd.readthedocs.io/en/latest/operator-manual/user-management/zitadel
    url: https://argocd.talmox.hera.home.karlsen.fr
    oidc.config: |
      name: Zitadel
      issuer: https://karlsen-xzy0yv.zitadel.cloud
      redirectURI: https://argocd.talmox.hera.home.karlsen.fr/auth/callback
      clientID: "352479117259590425"
      requestedScopes: ["openid", "profile", "email", "groups"]
      enablePKCEAuthentication: true
      preferredUsernameClaim: preferred_username
      logoutURL: https://karlsen-xzy0yv.zitadel.cloud/oidc/v1/end_session
    kustomize.buildOptions: --enable-helm --enable-alpha-plugins --enable-exec
  cmp:
    create: true
  params:
    server.insecure: true
    controller.diff.server.side: true
  rbac:
    scopes: '[groups]'
    policy.csv: |
      g, argocd_administrators, role:admin
      g, argocd_users, role:readonly
    policy.default: ''

crds:
  install: true
  keep: false

dex:
  enabled: false

repoServer:
  volumes:
    - name: custom-tools
      emptyDir: {}
    - name: sops-age
      secret:
        secretName: sops-age
  initContainers:
    - name: install-ksops
      image: viaductoss/ksops:v4
      command: ["/bin/sh", "-c"]
      args:
        - echo "Installing KSOPS and Kustomize...";
          mv ksops /custom-tools/;
          mv kustomize /custom-tools/;
          echo "Done.";
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
  volumeMounts:
    - mountPath: /usr/local/bin/kustomize
      name: custom-tools
      subPath: kustomize
    - mountPath: /usr/local/bin/ksops
      name: custom-tools
      subPath: ksops
    - name: sops-age
      mountPath: /.config/sops/age
  env:
    - name: XDG_CONFIG_HOME
      value: /.config
    - name: SOPS_AGE_KEY_FILE
      value: /.config/sops/age/keys.txt

server:
  httproute:
    enabled: true
    # labels: {}
    # annotations: {}
    parentRefs:
      - name: default-gateway
        namespace: gateway
        sectionName: https-wc-talmox-hera-home-karlsen-fr
    hostnames:
      - argocd.talmox.hera.home.karlsen.fr
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: /

  # To be fixed
  grpcroute:
    enabled: false
    # labels: {}
    # annotations: {}
    parentRefs:
      - kind: Gateway
        name: default-gateway
        namespace: gateway
        sectionName: https-wc-talmox-hera-home-karlsen-fr
    hostnames:
      - argocd.talmox.hera.home.karlsen.fr
    rules:
      - matches:
          - headers:
              - name: Content-Type
                value: application/grpc
