# Create: kubectl create secret --dry-run=client generic -n paperless paperless-secrets -o yaml --from-literal=paperless-redis=XX --from-literal=paperless-dbpass=XX --from-literal=paperless-secret-key=XX --from-literal=paperless-admin-password=XX
# Encrypt: sops -e Secret.paperless-secrets.yaml > Secret.paperless-secrets.enc.yaml
# Decrypt: sops -d Secret.paperless-secrets.enc.yaml > Secret.paperless-secrets.yaml
---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: paperless-secrets-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./Secret.paperless-secrets.enc.yaml
