#ENC[AES256_GCM,data:X4qGnxcOLHsO0RWlCOa/DNFUWe/CdE3iFSGzhuXXN1zFD2SzUAbYf/x806U2Cg67IxQlVcrjseO6HVXpx4rERNqS248y4cyDL2URMgc8AEEbvcmetrdMNw485JSBFvsqiLqIjrVZX6aEHPbfYCz/lxezfRFWVu/iMqDcNzGVMXCJR6uCBj6O+CHWlMWjWz1rHUsAgxRq2MSqvsXGjCNmIzYkIfyDqMzf4AGiF5JGbON8NI6/j+tSTTKXTxkL6kNxBnHPynTBpBrenBkiivuujFLUiAM2oD2ojRV5U3sCxQhzkRVyUZjyf/JYlpz23NAGbcscFM8=,iv:dhISYxhbmSUluVV6fgms5cDDs/03M2nVjh9JMwdzA54=,tag:nTtjFL71FL2pLqr6/57Nzg==,type:comment]
#ENC[AES256_GCM,data:7SdgZy0eJ99d/ApfrxRGKdizvK/yKezyeok24BoM0nu93zsaGO+HqgGesBSVAaHSdYsm14YIT6JrihU87wtRGHWg5vfPJ/XTuCKkG4cZzLkFG3U=,iv:XuaAdVqYXjmvoLAIYL0nJWxK6QImjx5xKMxjl17Yi4g=,tag:tMuXL09tC2XYzF6mrlPDww==,type:comment]
#ENC[AES256_GCM,data:yIZuzllemp+fOGG78+oermUnLB/OX9Z6+C/DKPJF1NzuVvGk/cFwLP7E7b2TFRzJzYD0kQPzvnZp2xszbMN4m2aFZwCh/jePFMi7BgtjKNRNdJ0=,iv:bTK6KhnmAqvJiaTExec2+ur//hOoKP9aK++J/ExYg04=,tag:hgKMYwZ405oKtRxS4TkWGQ==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: paperless-secrets
    namespace: paperless
    annotations:
        kustomize.config.k8s.io/behavior: replace
type: Opaque
data:
    paperless-admin-password: ENC[AES256_GCM,data:NGJ/gyVXiOG6hMT85Mwp4myGgvXqlTbMabmxfE4e8b7k6HsXpxjpuAV54kM=,iv:+Qz28Vc7Upg/mlb4mrRk98d9sh+f4PsKkrECWiKYJXg=,tag:UXur+0FKbybZuJRQU+sqFw==,type:str]
    paperless-dbpass: ENC[AES256_GCM,data:BArciuvznabFigN/JMCgdCKmv/0R3vbpjhta/VepvGRgmDLkOLBxtoz+lExd7C3w7UhISUaWlixKKbHMncyH2g==,iv:6WpjGp6gBHOim2fR6pTDpgohM9BQ8WvP0EzrS+ujau4=,tag:aCzzAbai72oWo8pFhumOXA==,type:str]
    paperless-redis: ENC[AES256_GCM,data:ITowzgP3TitK8hiVwRMpMEeiq4Yeln/G+byyEbxqVyTw4KWtRst1GbyUiDsa2zR6F6sLqjwF4YCqEtJR7tf04Ns71EJBDCnBt50SFiv4RZQjVMrSwO3fbKIVHew1fyprk/hs1TAtKJLltLS8DP/uTt5be6jFtF/j,iv:k+ug6pUxopxgDpVkDoZzFvSE63/kF57BdDRTbPE6eGE=,tag:SxjoYLF9M2V17YPte6Z9Lg==,type:str]
    paperless-secret-key: ENC[AES256_GCM,data:M0jdr9d+MHO+ajQlSzpG03TmHU6DpoIYHt38mhLUbz9i4WblMofjRFlvsEEX6IFbigyz5Uv/Gg2676YVFz1zcg==,iv:F4rL8wOONNmEJpqt/fzqrvPu1DN5e8fcVHUpmbwl1jw=,tag:jFLY10qsfakiXabaiMj0gA==,type:str]
sops:
    age:
        - recipient: age1gxk3ylhwfwe0nkhfu8pr08j5axz5y6qm50ntp0ncu0l6cx20fdrqw36n8a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySDlJYnlzbkc4MjFnVjVN
            RTMwYjJsaHhuTU0xVXo4eTNxc0Iwb01HVzE0Ck42VjZ6VlJ5eG03VldEVkQyRjdJ
            MkRESzY0ZFl3U2ZkNkl5akJuLzBuUkUKLS0tIGo3S0Z0NHVwTVpTa3pLcklYZXB2
            R2xBKytESy9mM1ZCUUROQzV2dGJ5bjAKqnViOH03T+tOzYOxgVJKNEPIIftMhvYq
            iSndISt31dO/ElvzI6ouxp7EffKgdlNQnnxyL45DO8UmZmKTHCC5JQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T00:07:12Z"
    mac: ENC[AES256_GCM,data:hzH2Oz9+cYH70PkD1J5F9C6kFgzbm3+2bATj6fK0YYGY/JsE+5XJXugEzbOWdWBO0HrKerhtCt6ibYhYEhMSwIM5oS7tjnyyoqjv6EbxsxTLU7V4w7KoXasTPgS1/hszT+ShiDPEXFxFuIpD9lb2VTo0GM+ILsHdplyp5gxMRVM=,iv:VMxuJCqB0kzx1H6nj3Z035lwgRpQBIQ7GSdpU055lyM=,tag:ed0ZWmJbEfYD+jcF3pRptg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
