# https://www.arthurkoziel.com/encrypting-k8s-secrets-with-sealed-secrets/
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - Namespace.yaml

helmCharts:
  - name: sealed-secrets
    repo: oci://registry-1.docker.io/bitnamicharts
    version: 2.18.0
    releaseName: sealed-secrets-controller
    namespace: sealed-secrets
    includeCRDs: true
    valuesFile: values.yaml
