---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - Namespace.yaml
  # - PersistentVolumeClaim.yaml
  - HTTPRoute.yaml

helmCharts:
  - name: portainer
    repo: https://portainer.github.io/k8s
    version: 2.33.6
    releaseName: portainer
    namespace: portainer
    valuesFile: values.yaml
