# Delete the claimRef from the PV to be able to use the PVC:
# kubectl edit pv XXXXX
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-portainer-pvc
  namespace: portainer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: longhorn-portainer-pv
