---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-portainer-pvc
  namespace: portainer
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: longhorn-portainer-volume
  resources:
    requests:
      storage: 2Gi
