---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: longhorn-portainer-pv
  labels:
    app.kubernetes.io/name: portainer
    recurring-job-group.longhorn.io/group1: enabled
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Mi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: longhorn-portainer-pvc
    namespace: portainer
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    # volumeAttributes:
    #   fromBackup: ""
    volumeHandle: longhorn-portainer-pv
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  volumeMode: Filesystem
