# Delete the claimRef from the PV to be able to use the PVC:
# kubectl edit pv XXXXX
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-portainer-pvc
  namespace: portainer
  labels:
    app.kubernetes.io/name: portainer
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: portainer
