# https://artifacthub.io/packages/helm/portainer/portainer
# https://github.com/portainer/k8s/blob/master/charts/portainer/README.md
---

service:
  type: ClusterIP

tls:
  force: false

image:
  tag: latest

ingress:
  enabled: false

persistence:
  enabled: false
  # size: "2Gi"
  # annotations: {}
  # storageClass: longhorn
  # existingClaim: longhorn-portainer-pvc
