---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: storage
  namespace: argocd
  labels:
    fr.karlsen: storage
spec:
  generators:
    - git:
        repoURL: https://github.com/sebastka/homelab.git
        revision: HEAD
        directories:
          - path: k8s/infrastructure/storage/*
  template:
    metadata:
      name: '{{ path.basename }}'
      labels:
        fr.karlsen: storage
    spec:
      project: storage
      source:
        plugin:
          name: kustomize-build-with-helm
        repoURL: https://github.com/sebastka/homelab.git
        targetRevision: HEAD
        path: '{{ path }}'
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        syncOptions:
          - ServerSideApply=true
        automated:
          prune: true
          selfHeal: true
          enabled: true
