# https://longhorn.io/docs/1.9.0/deploy/install/install-with-kubectl/
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      fr.karlsen: storage
      app.kubernetes.io/managed-by: argocd

resources:
  - AppProject.yaml
  - ApplicationSet.yaml
