---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: controllers
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/sebastka/homelab.git
  destinations:
    - namespace: argocd
      server: '*'
    - namespace: kube-system
      server: '*'
    - namespace: cert-manager
      server: '*'
    - namespace: portainer
      server: '*'
    - namespace: sealed-secrets
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
